### ISSUE TITLE
Орфографическая ошибка

### ISSUE THREAD

**Issue by missiamnq** [SaerWich/Trio#1]
1. при регистрации
![2](https://user-images.githubusercontent.com/90756296/145867680-b8a2f7ac-326a-4cad-a0d1-963d955fda64.png)
если ввести пароль длиной <9 => вылезает окно ошибки
2. допущена орфографическая ошибка в слове "длина"
![1](https://user-images.githubusercontent.com/90756296/145867836-0f591db3-3ff0-46c2-a55b-c54a25b44b55.png)
а также неправильно построено предложение по синтаксическим нормам 
ожидаемый результат:  "пароль слишком простой, убедитесь, что ваш пароль имеет длину больше чем 9 символов, а так же содержит как цифры, так и буквы. Длина вашего пароля: 7 символов"

**Comment by SaerWich** [comment]
🗿
